export const INCREMENT_CURRENT_STEP = 'APP/INCREMENT_CURRENT_STEP';
export const DECREMENT_CURRENT_STEP = 'APP/DECREMENT_CURRENT_STEP';
export const SET_PROGRAM = 'DATA/SET_PROGRAM';
export const SET_TOTAL_SUM = 'DATA/SET_TOTAL_SUM';
export const SET_TERM_PERIOD = 'DATA/SET_TERM_PERIOD';
export const SET_FIRST_SUM = 'DATA/SET_FIRST_SUM';
export const SET_MONTH_SUM = 'DATA/SET_MONTH_SUM';